set(LOGGER_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external")
set(LOGGER_INCLUDE_DIRS ${LOGGER_INCLUDE_DIR})
set(LOGGER_LIBRARY "logger")
set(LOGGER_LIBRARIES ${LOGGER_LIBRARY})

add_subdirectory("${LOGGER_INCLUDE_DIR}/logger")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(logger DEFAULT_MSG LOGGER_LIBRARIES LOGGER_INCLUDE_DIR LOGGER_INCLUDE_DIRS)
MESSAGE( STATUS "findlogger: " ${LOGGER_INCLUDE_DIR} )
mark_as_advanced(LOGGER_LIBRARY LOGGER_LIBRARIES LOGGER_INCLUDE_DIR LOGGER_INCLUDE_DIRS)
